apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "worker.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "worker.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                # The secret resource we are reading from
                name: {{ include "worker.fullname" . }}
          env:
          - name: RabbitMq__Host
            value: {{ .Values.env.RabbitMq.Host }}
          - name: RabbitMq__VirtualHost
            value: {{ .Values.env.RabbitMq.VirtualHost }}
          - name: RabbitMq__Username
            valueFrom:
              secretKeyRef:
                # The secret resource we are reading from
                name: {{ include "worker.fullname" . }}
                # This key is read from our helm-secret secrets.yaml
                key: RabbitMqUsername
          - name: RabbitMq__Password
            valueFrom:
              secretKeyRef:
                # The secret resource we are reading from
                name: {{ include "worker.fullname" . }}
                # This key is read from our helm-secret secrets.yaml
                key: RabbitMqPassword
          - name: Serilog__WriteTo__0__Args__serverUrl
            value: {{ .Values.env.Serilog.Url }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP