# Declare variables to be passed into your templates.

replicaCount: 0

image:
  repository: localhost:32000/demo-workers-user
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: registry

env:
  RabbitMq:
    Host: rabbitmq.dev.svc.cluster.local
    VirtualHost: /
    QueueName: Demo.Workers.User.UserCreatedConsumer
  Serilog:
    Url: http://my-seq.dev:5341

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
